program abi_test;
{$mode objfpc}{$H+}
uses parade;
var
  v_pd_font_metrics: pd_font_metrics;
  v_pd_outline_sink: pd_outline_sink;
  v_pd_glyph_image: pd_glyph_image;
  v_pd_style: pd_style;
  v_pd_params: pd_params;
  v_pd_break_info: pd_break_info;
  v_pd_line: pd_line;
  v_pd_glyph: pd_glyph;
  v_pd_pos: pd_pos;
  v_pd_range: pd_range;
  v_pd_block_info: pd_block_info;
  v_pd_char_props: pd_char_props;
  v_pd_para_props: pd_para_props;
  v_pd_tab_stop: pd_tab_stop;
  v_pd_list_level: pd_list_level;
  v_pd_run: pd_run;
  v_pd_inline: pd_inline;
  v_pd_para_attrs: pd_para_attrs;
  v_pd_float_props: pd_float_props;
  v_pd_section_props: pd_section_props;
  v_pd_table_props: pd_table_props;
  v_pd_cell_props: pd_cell_props;
  v_pd_change: pd_change;
  v_pd_layout_info: pd_layout_info;
  v_pd_page_info: pd_page_info;
  v_pd_draw: pd_draw;
  v_pd_pdf_options: pd_pdf_options;
begin
  WriteLn('pd_font_metrics ', SizeOf(pd_font_metrics));
  WriteLn('pd_font_metrics.units_per_em ', PtrUInt(@v_pd_font_metrics.units_per_em) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.ascender ', PtrUInt(@v_pd_font_metrics.ascender) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.descender ', PtrUInt(@v_pd_font_metrics.descender) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.line_gap ', PtrUInt(@v_pd_font_metrics.line_gap) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.x_height ', PtrUInt(@v_pd_font_metrics.x_height) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.cap_height ', PtrUInt(@v_pd_font_metrics.cap_height) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.num_glyphs ', PtrUInt(@v_pd_font_metrics.num_glyphs) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_font_metrics.has_kerning ', PtrUInt(@v_pd_font_metrics.has_kerning) - PtrUInt(@v_pd_font_metrics));
  WriteLn('pd_outline_sink ', SizeOf(pd_outline_sink));
  WriteLn('pd_outline_sink.move_to ', PtrUInt(@v_pd_outline_sink.move_to) - PtrUInt(@v_pd_outline_sink));
  WriteLn('pd_outline_sink.line_to ', PtrUInt(@v_pd_outline_sink.line_to) - PtrUInt(@v_pd_outline_sink));
  WriteLn('pd_outline_sink.quad_to ', PtrUInt(@v_pd_outline_sink.quad_to) - PtrUInt(@v_pd_outline_sink));
  WriteLn('pd_outline_sink.cubic_to ', PtrUInt(@v_pd_outline_sink.cubic_to) - PtrUInt(@v_pd_outline_sink));
  WriteLn('pd_outline_sink.close ', PtrUInt(@v_pd_outline_sink.close) - PtrUInt(@v_pd_outline_sink));
  WriteLn('pd_glyph_image ', SizeOf(pd_glyph_image));
  WriteLn('pd_glyph_image.width ', PtrUInt(@v_pd_glyph_image.width) - PtrUInt(@v_pd_glyph_image));
  WriteLn('pd_glyph_image.height ', PtrUInt(@v_pd_glyph_image.height) - PtrUInt(@v_pd_glyph_image));
  WriteLn('pd_glyph_image.left ', PtrUInt(@v_pd_glyph_image.left) - PtrUInt(@v_pd_glyph_image));
  WriteLn('pd_glyph_image.top ', PtrUInt(@v_pd_glyph_image.top) - PtrUInt(@v_pd_glyph_image));
  WriteLn('pd_style ', SizeOf(pd_style));
  WriteLn('pd_style.font ', PtrUInt(@v_pd_style.font) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.size ', PtrUInt(@v_pd_style.size) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.space_stretch ', PtrUInt(@v_pd_style.space_stretch) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.space_shrink ', PtrUInt(@v_pd_style.space_shrink) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.kerning ', PtrUInt(@v_pd_style.kerning) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.color ', PtrUInt(@v_pd_style.color) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.user ', PtrUInt(@v_pd_style.user) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.hyph ', PtrUInt(@v_pd_style.hyph) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.text_case ', PtrUInt(@v_pd_style.text_case) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.letter_space ', PtrUInt(@v_pd_style.letter_space) - PtrUInt(@v_pd_style));
  WriteLn('pd_style.hidden ', PtrUInt(@v_pd_style.hidden) - PtrUInt(@v_pd_style));
  WriteLn('pd_params ', SizeOf(pd_params));
  WriteLn('pd_params.mode ', PtrUInt(@v_pd_params.mode) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.align ', PtrUInt(@v_pd_params.align) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.width ', PtrUInt(@v_pd_params.width) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.indent ', PtrUInt(@v_pd_params.indent) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.line_penalty ', PtrUInt(@v_pd_params.line_penalty) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.adj_demerits ', PtrUInt(@v_pd_params.adj_demerits) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.double_hyphen_demerits ', PtrUInt(@v_pd_params.double_hyphen_demerits) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.final_hyphen_demerits ', PtrUInt(@v_pd_params.final_hyphen_demerits) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.hyphen_penalty ', PtrUInt(@v_pd_params.hyphen_penalty) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.ex_hyphen_penalty ', PtrUInt(@v_pd_params.ex_hyphen_penalty) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.tex_badness ', PtrUInt(@v_pd_params.tex_badness) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.rag_stretch ', PtrUInt(@v_pd_params.rag_stretch) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.baseline_skip ', PtrUInt(@v_pd_params.baseline_skip) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.line_spacing ', PtrUInt(@v_pd_params.line_spacing) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.hysteresis ', PtrUInt(@v_pd_params.hysteresis) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.freeze_offset ', PtrUInt(@v_pd_params.freeze_offset) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.direction ', PtrUInt(@v_pd_params.direction) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.looseness ', PtrUInt(@v_pd_params.looseness) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.protrusion ', PtrUInt(@v_pd_params.protrusion) - PtrUInt(@v_pd_params));
  WriteLn('pd_params.expansion ', PtrUInt(@v_pd_params.expansion) - PtrUInt(@v_pd_params));
  WriteLn('pd_break_info ', SizeOf(pd_break_info));
  WriteLn('pd_break_info.lines ', PtrUInt(@v_pd_break_info.lines) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.demerits ', PtrUInt(@v_pd_break_info.demerits) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.overfull ', PtrUInt(@v_pd_break_info.overfull) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.underfull ', PtrUInt(@v_pd_break_info.underfull) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.reused_breakpoints ', PtrUInt(@v_pd_break_info.reused_breakpoints) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.frozen_lines ', PtrUInt(@v_pd_break_info.frozen_lines) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_break_info.height ', PtrUInt(@v_pd_break_info.height) - PtrUInt(@v_pd_break_info));
  WriteLn('pd_line ', SizeOf(pd_line));
  WriteLn('pd_line.text_start ', PtrUInt(@v_pd_line.text_start) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.text_end ', PtrUInt(@v_pd_line.text_end) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.x ', PtrUInt(@v_pd_line.x) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.baseline ', PtrUInt(@v_pd_line.baseline) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.width ', PtrUInt(@v_pd_line.width) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.ascent ', PtrUInt(@v_pd_line.ascent) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.descent ', PtrUInt(@v_pd_line.descent) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.ratio ', PtrUInt(@v_pd_line.ratio) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.badness ', PtrUInt(@v_pd_line.badness) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.hyphenated ', PtrUInt(@v_pd_line.hyphenated) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.overfull ', PtrUInt(@v_pd_line.overfull) - PtrUInt(@v_pd_line));
  WriteLn('pd_line.underfull ', PtrUInt(@v_pd_line.underfull) - PtrUInt(@v_pd_line));
  WriteLn('pd_glyph ', SizeOf(pd_glyph));
  WriteLn('pd_glyph.glyph ', PtrUInt(@v_pd_glyph.glyph) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.cluster ', PtrUInt(@v_pd_glyph.cluster) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.x ', PtrUInt(@v_pd_glyph.x) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.y ', PtrUInt(@v_pd_glyph.y) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.advance ', PtrUInt(@v_pd_glyph.advance) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.style ', PtrUInt(@v_pd_glyph.style) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.kind ', PtrUInt(@v_pd_glyph.kind) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.user ', PtrUInt(@v_pd_glyph.user) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_glyph.scale ', PtrUInt(@v_pd_glyph.scale) - PtrUInt(@v_pd_glyph));
  WriteLn('pd_pos ', SizeOf(pd_pos));
  WriteLn('pd_pos.block ', PtrUInt(@v_pd_pos.block) - PtrUInt(@v_pd_pos));
  WriteLn('pd_pos.offset ', PtrUInt(@v_pd_pos.offset) - PtrUInt(@v_pd_pos));
  WriteLn('pd_range ', SizeOf(pd_range));
  WriteLn('pd_range.start ', PtrUInt(@v_pd_range.start) - PtrUInt(@v_pd_range));
  WriteLn('pd_range.end ', PtrUInt(@v_pd_range.finish) - PtrUInt(@v_pd_range));
  WriteLn('pd_block_info ', SizeOf(pd_block_info));
  WriteLn('pd_block_info.kind ', PtrUInt(@v_pd_block_info.kind) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.id ', PtrUInt(@v_pd_block_info.id) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.parent ', PtrUInt(@v_pd_block_info.parent) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.child_count ', PtrUInt(@v_pd_block_info.child_count) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.index ', PtrUInt(@v_pd_block_info.index) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.role ', PtrUInt(@v_pd_block_info.role) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.level ', PtrUInt(@v_pd_block_info.level) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.list_level ', PtrUInt(@v_pd_block_info.list_level) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.style ', PtrUInt(@v_pd_block_info.style) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.list ', PtrUInt(@v_pd_block_info.list) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.break_kind ', PtrUInt(@v_pd_block_info.break_kind) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.text_length ', PtrUInt(@v_pd_block_info.text_length) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_block_info.revision ', PtrUInt(@v_pd_block_info.revision) - PtrUInt(@v_pd_block_info));
  WriteLn('pd_char_props ', SizeOf(pd_char_props));
  WriteLn('pd_char_props.mask ', PtrUInt(@v_pd_char_props.mask) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.family ', PtrUInt(@v_pd_char_props.family) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.size ', PtrUInt(@v_pd_char_props.size) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.weight ', PtrUInt(@v_pd_char_props.weight) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.italic ', PtrUInt(@v_pd_char_props.italic) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.color ', PtrUInt(@v_pd_char_props.color) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.background ', PtrUInt(@v_pd_char_props.background) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.underline ', PtrUInt(@v_pd_char_props.underline) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.strike ', PtrUInt(@v_pd_char_props.strike) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.shift ', PtrUInt(@v_pd_char_props.shift) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.letter_space ', PtrUInt(@v_pd_char_props.letter_space) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.kerning ', PtrUInt(@v_pd_char_props.kerning) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.lang ', PtrUInt(@v_pd_char_props.lang) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.small_caps ', PtrUInt(@v_pd_char_props.small_caps) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.link_target ', PtrUInt(@v_pd_char_props.link_target) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.caps ', PtrUInt(@v_pd_char_props.caps) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.hidden ', PtrUInt(@v_pd_char_props.hidden) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_char_props.position ', PtrUInt(@v_pd_char_props.position) - PtrUInt(@v_pd_char_props));
  WriteLn('pd_para_props ', SizeOf(pd_para_props));
  WriteLn('pd_para_props.mask ', PtrUInt(@v_pd_para_props.mask) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.align ', PtrUInt(@v_pd_para_props.align) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.indent_left ', PtrUInt(@v_pd_para_props.indent_left) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.indent_right ', PtrUInt(@v_pd_para_props.indent_right) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.indent_first ', PtrUInt(@v_pd_para_props.indent_first) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.space_before ', PtrUInt(@v_pd_para_props.space_before) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.space_after ', PtrUInt(@v_pd_para_props.space_after) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.line_spacing ', PtrUInt(@v_pd_para_props.line_spacing) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.keep_with_next ', PtrUInt(@v_pd_para_props.keep_with_next) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.keep_lines ', PtrUInt(@v_pd_para_props.keep_lines) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.widows ', PtrUInt(@v_pd_para_props.widows) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.orphans ', PtrUInt(@v_pd_para_props.orphans) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.page_break_before ', PtrUInt(@v_pd_para_props.page_break_before) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.hyphenate ', PtrUInt(@v_pd_para_props.hyphenate) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.break_mode ', PtrUInt(@v_pd_para_props.break_mode) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.next_style ', PtrUInt(@v_pd_para_props.next_style) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.border_color ', PtrUInt(@v_pd_para_props.border_color) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.border_width ', PtrUInt(@v_pd_para_props.border_width) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.shading ', PtrUInt(@v_pd_para_props.shading) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.direction ', PtrUInt(@v_pd_para_props.direction) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.ntabs ', PtrUInt(@v_pd_para_props.ntabs) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.tabs ', PtrUInt(@v_pd_para_props.tabs) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.tab_interval ', PtrUInt(@v_pd_para_props.tab_interval) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.contextual ', PtrUInt(@v_pd_para_props.contextual) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.border_sides ', PtrUInt(@v_pd_para_props.border_sides) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_para_props.border_space ', PtrUInt(@v_pd_para_props.border_space) - PtrUInt(@v_pd_para_props));
  WriteLn('pd_tab_stop ', SizeOf(pd_tab_stop));
  WriteLn('pd_tab_stop.position ', PtrUInt(@v_pd_tab_stop.position) - PtrUInt(@v_pd_tab_stop));
  WriteLn('pd_tab_stop.align ', PtrUInt(@v_pd_tab_stop.align) - PtrUInt(@v_pd_tab_stop));
  WriteLn('pd_tab_stop.leader ', PtrUInt(@v_pd_tab_stop.leader) - PtrUInt(@v_pd_tab_stop));
  WriteLn('pd_list_level ', SizeOf(pd_list_level));
  WriteLn('pd_list_level.format ', PtrUInt(@v_pd_list_level.format) - PtrUInt(@v_pd_list_level));
  WriteLn('pd_list_level.start ', PtrUInt(@v_pd_list_level.start) - PtrUInt(@v_pd_list_level));
  WriteLn('pd_list_level.text ', PtrUInt(@v_pd_list_level.text) - PtrUInt(@v_pd_list_level));
  WriteLn('pd_list_level.indent ', PtrUInt(@v_pd_list_level.indent) - PtrUInt(@v_pd_list_level));
  WriteLn('pd_list_level.hanging ', PtrUInt(@v_pd_list_level.hanging) - PtrUInt(@v_pd_list_level));
  WriteLn('pd_run ', SizeOf(pd_run));
  WriteLn('pd_run.start ', PtrUInt(@v_pd_run.start) - PtrUInt(@v_pd_run));
  WriteLn('pd_run.end ', PtrUInt(@v_pd_run.finish) - PtrUInt(@v_pd_run));
  WriteLn('pd_run.format ', PtrUInt(@v_pd_run.format) - PtrUInt(@v_pd_run));
  WriteLn('pd_inline ', SizeOf(pd_inline));
  WriteLn('pd_inline.kind ', PtrUInt(@v_pd_inline.kind) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.resource ', PtrUInt(@v_pd_inline.resource) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.width ', PtrUInt(@v_pd_inline.width) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.height ', PtrUInt(@v_pd_inline.height) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.depth ', PtrUInt(@v_pd_inline.depth) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.field ', PtrUInt(@v_pd_inline.field) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.target ', PtrUInt(@v_pd_inline.target) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.level ', PtrUInt(@v_pd_inline.level) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.name ', PtrUInt(@v_pd_inline.name) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.source ', PtrUInt(@v_pd_inline.source) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.source_len ', PtrUInt(@v_pd_inline.source_len) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.user ', PtrUInt(@v_pd_inline.user) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.title ', PtrUInt(@v_pd_inline.title) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.title_len ', PtrUInt(@v_pd_inline.title_len) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.alt ', PtrUInt(@v_pd_inline.alt) - PtrUInt(@v_pd_inline));
  WriteLn('pd_inline.alt_len ', PtrUInt(@v_pd_inline.alt_len) - PtrUInt(@v_pd_inline));
  WriteLn('pd_para_attrs ', SizeOf(pd_para_attrs));
  WriteLn('pd_para_attrs.quote_depth ', PtrUInt(@v_pd_para_attrs.quote_depth) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_para_attrs.task ', PtrUInt(@v_pd_para_attrs.task) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_para_attrs.loose ', PtrUInt(@v_pd_para_attrs.loose) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_para_attrs.lang ', PtrUInt(@v_pd_para_attrs.lang) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_para_attrs.cont ', PtrUInt(@v_pd_para_attrs.cont) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_para_attrs.div_class ', PtrUInt(@v_pd_para_attrs.div_class) - PtrUInt(@v_pd_para_attrs));
  WriteLn('pd_float_props ', SizeOf(pd_float_props));
  WriteLn('pd_float_props.placement ', PtrUInt(@v_pd_float_props.placement) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.wrap ', PtrUInt(@v_pd_float_props.wrap) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.width ', PtrUInt(@v_pd_float_props.width) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.width_fraction ', PtrUInt(@v_pd_float_props.width_fraction) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.span_columns ', PtrUInt(@v_pd_float_props.span_columns) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.gap ', PtrUInt(@v_pd_float_props.gap) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_float_props.sequence ', PtrUInt(@v_pd_float_props.sequence) - PtrUInt(@v_pd_float_props));
  WriteLn('pd_section_props ', SizeOf(pd_section_props));
  WriteLn('pd_section_props.page_width ', PtrUInt(@v_pd_section_props.page_width) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.page_height ', PtrUInt(@v_pd_section_props.page_height) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.margin_top ', PtrUInt(@v_pd_section_props.margin_top) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.margin_bottom ', PtrUInt(@v_pd_section_props.margin_bottom) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.margin_left ', PtrUInt(@v_pd_section_props.margin_left) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.margin_right ', PtrUInt(@v_pd_section_props.margin_right) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.header_distance ', PtrUInt(@v_pd_section_props.header_distance) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.footer_distance ', PtrUInt(@v_pd_section_props.footer_distance) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.columns ', PtrUInt(@v_pd_section_props.columns) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.column_gap ', PtrUInt(@v_pd_section_props.column_gap) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.first_page_number ', PtrUInt(@v_pd_section_props.first_page_number) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.page_number_format ', PtrUInt(@v_pd_section_props.page_number_format) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.title_page ', PtrUInt(@v_pd_section_props.title_page) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.facing_pages ', PtrUInt(@v_pd_section_props.facing_pages) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.header ', PtrUInt(@v_pd_section_props.header) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.header_first ', PtrUInt(@v_pd_section_props.header_first) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.header_even ', PtrUInt(@v_pd_section_props.header_even) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.footer ', PtrUInt(@v_pd_section_props.footer) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.footer_first ', PtrUInt(@v_pd_section_props.footer_first) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.footer_even ', PtrUInt(@v_pd_section_props.footer_even) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.continuous ', PtrUInt(@v_pd_section_props.continuous) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.page_breaking ', PtrUInt(@v_pd_section_props.page_breaking) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.footnote_skip ', PtrUInt(@v_pd_section_props.footnote_skip) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_section_props.add_spacing ', PtrUInt(@v_pd_section_props.add_spacing) - PtrUInt(@v_pd_section_props));
  WriteLn('pd_table_props ', SizeOf(pd_table_props));
  WriteLn('pd_table_props.width ', PtrUInt(@v_pd_table_props.width) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.align ', PtrUInt(@v_pd_table_props.align) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.header_rows ', PtrUInt(@v_pd_table_props.header_rows) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.cell_padding ', PtrUInt(@v_pd_table_props.cell_padding) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.border ', PtrUInt(@v_pd_table_props.border) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.border_color ', PtrUInt(@v_pd_table_props.border_color) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.ncols ', PtrUInt(@v_pd_table_props.ncols) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.col_width ', PtrUInt(@v_pd_table_props.col_width) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.indent ', PtrUInt(@v_pd_table_props.indent) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.width_pct ', PtrUInt(@v_pd_table_props.width_pct) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.border_sides ', PtrUInt(@v_pd_table_props.border_sides) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_table_props.cell_padding_v ', PtrUInt(@v_pd_table_props.cell_padding_v) - PtrUInt(@v_pd_table_props));
  WriteLn('pd_cell_props ', SizeOf(pd_cell_props));
  WriteLn('pd_cell_props.col_span ', PtrUInt(@v_pd_cell_props.col_span) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.valign ', PtrUInt(@v_pd_cell_props.valign) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.background ', PtrUInt(@v_pd_cell_props.background) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.merge_up ', PtrUInt(@v_pd_cell_props.merge_up) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.min_height ', PtrUInt(@v_pd_cell_props.min_height) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.border_set ', PtrUInt(@v_pd_cell_props.border_set) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.border_on ', PtrUInt(@v_pd_cell_props.border_on) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.border_width ', PtrUInt(@v_pd_cell_props.border_width) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_cell_props.border_color ', PtrUInt(@v_pd_cell_props.border_color) - PtrUInt(@v_pd_cell_props));
  WriteLn('pd_change ', SizeOf(pd_change));
  WriteLn('pd_change.kind ', PtrUInt(@v_pd_change.kind) - PtrUInt(@v_pd_change));
  WriteLn('pd_change.block ', PtrUInt(@v_pd_change.block) - PtrUInt(@v_pd_change));
  WriteLn('pd_change.style ', PtrUInt(@v_pd_change.style) - PtrUInt(@v_pd_change));
  WriteLn('pd_change.revision ', PtrUInt(@v_pd_change.revision) - PtrUInt(@v_pd_change));
  WriteLn('pd_layout_info ', SizeOf(pd_layout_info));
  WriteLn('pd_layout_info.pages ', PtrUInt(@v_pd_layout_info.pages) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_layout_info.paragraphs_broken ', PtrUInt(@v_pd_layout_info.paragraphs_broken) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_layout_info.paragraphs_reused ', PtrUInt(@v_pd_layout_info.paragraphs_reused) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_layout_info.float_pages ', PtrUInt(@v_pd_layout_info.float_pages) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_layout_info.overfull ', PtrUInt(@v_pd_layout_info.overfull) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_layout_info.variants ', PtrUInt(@v_pd_layout_info.variants) - PtrUInt(@v_pd_layout_info));
  WriteLn('pd_page_info ', SizeOf(pd_page_info));
  WriteLn('pd_page_info.width ', PtrUInt(@v_pd_page_info.width) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.height ', PtrUInt(@v_pd_page_info.height) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.section ', PtrUInt(@v_pd_page_info.section) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.number ', PtrUInt(@v_pd_page_info.number) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.label ', PtrUInt(@v_pd_page_info.label_) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.float_page ', PtrUInt(@v_pd_page_info.float_page) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.first ', PtrUInt(@v_pd_page_info.first) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_page_info.last ', PtrUInt(@v_pd_page_info.last) - PtrUInt(@v_pd_page_info));
  WriteLn('pd_draw ', SizeOf(pd_draw));
  WriteLn('pd_draw.kind ', PtrUInt(@v_pd_draw.kind) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.x ', PtrUInt(@v_pd_draw.x) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.y ', PtrUInt(@v_pd_draw.y) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.w ', PtrUInt(@v_pd_draw.w) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.h ', PtrUInt(@v_pd_draw.h) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.glyph ', PtrUInt(@v_pd_draw.glyph) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.font ', PtrUInt(@v_pd_draw.font) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.size ', PtrUInt(@v_pd_draw.size) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.color ', PtrUInt(@v_pd_draw.color) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.resource ', PtrUInt(@v_pd_draw.resource) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.block ', PtrUInt(@v_pd_draw.block) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.offset ', PtrUInt(@v_pd_draw.offset) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.region ', PtrUInt(@v_pd_draw.region) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.text ', PtrUInt(@v_pd_draw.text) - PtrUInt(@v_pd_draw));
  WriteLn('pd_draw.scale ', PtrUInt(@v_pd_draw.scale) - PtrUInt(@v_pd_draw));
  WriteLn('pd_pdf_options ', SizeOf(pd_pdf_options));
  WriteLn('pd_pdf_options.compress ', PtrUInt(@v_pd_pdf_options.compress) - PtrUInt(@v_pd_pdf_options));
  WriteLn('pd_pdf_options.outlines ', PtrUInt(@v_pd_pdf_options.outlines) - PtrUInt(@v_pd_pdf_options));
  WriteLn('pd_pdf_options.title ', PtrUInt(@v_pd_pdf_options.title) - PtrUInt(@v_pd_pdf_options));
  WriteLn('pd_pdf_options.author ', PtrUInt(@v_pd_pdf_options.author) - PtrUInt(@v_pd_pdf_options));
end.
