#include <stdio.h>
#include <stddef.h>
#include "parade_layout.h"
int main(void) {
    printf("pd_font_metrics %zu\n", sizeof(pd_font_metrics));
    printf("pd_font_metrics.units_per_em %zu\n", offsetof(pd_font_metrics, units_per_em));
    printf("pd_font_metrics.ascender %zu\n", offsetof(pd_font_metrics, ascender));
    printf("pd_font_metrics.descender %zu\n", offsetof(pd_font_metrics, descender));
    printf("pd_font_metrics.line_gap %zu\n", offsetof(pd_font_metrics, line_gap));
    printf("pd_font_metrics.x_height %zu\n", offsetof(pd_font_metrics, x_height));
    printf("pd_font_metrics.cap_height %zu\n", offsetof(pd_font_metrics, cap_height));
    printf("pd_font_metrics.num_glyphs %zu\n", offsetof(pd_font_metrics, num_glyphs));
    printf("pd_font_metrics.has_kerning %zu\n", offsetof(pd_font_metrics, has_kerning));
    printf("pd_outline_sink %zu\n", sizeof(pd_outline_sink));
    printf("pd_outline_sink.move_to %zu\n", offsetof(pd_outline_sink, move_to));
    printf("pd_outline_sink.line_to %zu\n", offsetof(pd_outline_sink, line_to));
    printf("pd_outline_sink.quad_to %zu\n", offsetof(pd_outline_sink, quad_to));
    printf("pd_outline_sink.cubic_to %zu\n", offsetof(pd_outline_sink, cubic_to));
    printf("pd_outline_sink.close %zu\n", offsetof(pd_outline_sink, close));
    printf("pd_glyph_image %zu\n", sizeof(pd_glyph_image));
    printf("pd_glyph_image.width %zu\n", offsetof(pd_glyph_image, width));
    printf("pd_glyph_image.height %zu\n", offsetof(pd_glyph_image, height));
    printf("pd_glyph_image.left %zu\n", offsetof(pd_glyph_image, left));
    printf("pd_glyph_image.top %zu\n", offsetof(pd_glyph_image, top));
    printf("pd_style %zu\n", sizeof(pd_style));
    printf("pd_style.font %zu\n", offsetof(pd_style, font));
    printf("pd_style.size %zu\n", offsetof(pd_style, size));
    printf("pd_style.space_stretch %zu\n", offsetof(pd_style, space_stretch));
    printf("pd_style.space_shrink %zu\n", offsetof(pd_style, space_shrink));
    printf("pd_style.kerning %zu\n", offsetof(pd_style, kerning));
    printf("pd_style.color %zu\n", offsetof(pd_style, color));
    printf("pd_style.user %zu\n", offsetof(pd_style, user));
    printf("pd_style.hyph %zu\n", offsetof(pd_style, hyph));
    printf("pd_style.text_case %zu\n", offsetof(pd_style, text_case));
    printf("pd_style.letter_space %zu\n", offsetof(pd_style, letter_space));
    printf("pd_style.hidden %zu\n", offsetof(pd_style, hidden));
    printf("pd_params %zu\n", sizeof(pd_params));
    printf("pd_params.mode %zu\n", offsetof(pd_params, mode));
    printf("pd_params.align %zu\n", offsetof(pd_params, align));
    printf("pd_params.width %zu\n", offsetof(pd_params, width));
    printf("pd_params.indent %zu\n", offsetof(pd_params, indent));
    printf("pd_params.line_penalty %zu\n", offsetof(pd_params, line_penalty));
    printf("pd_params.adj_demerits %zu\n", offsetof(pd_params, adj_demerits));
    printf("pd_params.double_hyphen_demerits %zu\n", offsetof(pd_params, double_hyphen_demerits));
    printf("pd_params.final_hyphen_demerits %zu\n", offsetof(pd_params, final_hyphen_demerits));
    printf("pd_params.hyphen_penalty %zu\n", offsetof(pd_params, hyphen_penalty));
    printf("pd_params.ex_hyphen_penalty %zu\n", offsetof(pd_params, ex_hyphen_penalty));
    printf("pd_params.tex_badness %zu\n", offsetof(pd_params, tex_badness));
    printf("pd_params.rag_stretch %zu\n", offsetof(pd_params, rag_stretch));
    printf("pd_params.baseline_skip %zu\n", offsetof(pd_params, baseline_skip));
    printf("pd_params.line_spacing %zu\n", offsetof(pd_params, line_spacing));
    printf("pd_params.hysteresis %zu\n", offsetof(pd_params, hysteresis));
    printf("pd_params.freeze_offset %zu\n", offsetof(pd_params, freeze_offset));
    printf("pd_params.direction %zu\n", offsetof(pd_params, direction));
    printf("pd_params.looseness %zu\n", offsetof(pd_params, looseness));
    printf("pd_params.protrusion %zu\n", offsetof(pd_params, protrusion));
    printf("pd_params.expansion %zu\n", offsetof(pd_params, expansion));
    printf("pd_params.full_lines %zu\n", offsetof(pd_params, full_lines));
    printf("pd_params.line_grid %zu\n", offsetof(pd_params, line_grid));
    printf("pd_break_info %zu\n", sizeof(pd_break_info));
    printf("pd_break_info.lines %zu\n", offsetof(pd_break_info, lines));
    printf("pd_break_info.demerits %zu\n", offsetof(pd_break_info, demerits));
    printf("pd_break_info.overfull %zu\n", offsetof(pd_break_info, overfull));
    printf("pd_break_info.underfull %zu\n", offsetof(pd_break_info, underfull));
    printf("pd_break_info.reused_breakpoints %zu\n", offsetof(pd_break_info, reused_breakpoints));
    printf("pd_break_info.frozen_lines %zu\n", offsetof(pd_break_info, frozen_lines));
    printf("pd_break_info.height %zu\n", offsetof(pd_break_info, height));
    printf("pd_line %zu\n", sizeof(pd_line));
    printf("pd_line.text_start %zu\n", offsetof(pd_line, text_start));
    printf("pd_line.text_end %zu\n", offsetof(pd_line, text_end));
    printf("pd_line.x %zu\n", offsetof(pd_line, x));
    printf("pd_line.baseline %zu\n", offsetof(pd_line, baseline));
    printf("pd_line.width %zu\n", offsetof(pd_line, width));
    printf("pd_line.ascent %zu\n", offsetof(pd_line, ascent));
    printf("pd_line.descent %zu\n", offsetof(pd_line, descent));
    printf("pd_line.ratio %zu\n", offsetof(pd_line, ratio));
    printf("pd_line.badness %zu\n", offsetof(pd_line, badness));
    printf("pd_line.hyphenated %zu\n", offsetof(pd_line, hyphenated));
    printf("pd_line.overfull %zu\n", offsetof(pd_line, overfull));
    printf("pd_line.underfull %zu\n", offsetof(pd_line, underfull));
    printf("pd_glyph %zu\n", sizeof(pd_glyph));
    printf("pd_glyph.glyph %zu\n", offsetof(pd_glyph, glyph));
    printf("pd_glyph.cluster %zu\n", offsetof(pd_glyph, cluster));
    printf("pd_glyph.x %zu\n", offsetof(pd_glyph, x));
    printf("pd_glyph.y %zu\n", offsetof(pd_glyph, y));
    printf("pd_glyph.advance %zu\n", offsetof(pd_glyph, advance));
    printf("pd_glyph.style %zu\n", offsetof(pd_glyph, style));
    printf("pd_glyph.kind %zu\n", offsetof(pd_glyph, kind));
    printf("pd_glyph.user %zu\n", offsetof(pd_glyph, user));
    printf("pd_glyph.scale %zu\n", offsetof(pd_glyph, scale));
    printf("pd_pos %zu\n", sizeof(pd_pos));
    printf("pd_pos.block %zu\n", offsetof(pd_pos, block));
    printf("pd_pos.offset %zu\n", offsetof(pd_pos, offset));
    printf("pd_range %zu\n", sizeof(pd_range));
    printf("pd_range.start %zu\n", offsetof(pd_range, start));
    printf("pd_range.end %zu\n", offsetof(pd_range, end));
    printf("pd_block_info %zu\n", sizeof(pd_block_info));
    printf("pd_block_info.kind %zu\n", offsetof(pd_block_info, kind));
    printf("pd_block_info.id %zu\n", offsetof(pd_block_info, id));
    printf("pd_block_info.parent %zu\n", offsetof(pd_block_info, parent));
    printf("pd_block_info.child_count %zu\n", offsetof(pd_block_info, child_count));
    printf("pd_block_info.index %zu\n", offsetof(pd_block_info, index));
    printf("pd_block_info.role %zu\n", offsetof(pd_block_info, role));
    printf("pd_block_info.level %zu\n", offsetof(pd_block_info, level));
    printf("pd_block_info.list_level %zu\n", offsetof(pd_block_info, list_level));
    printf("pd_block_info.style %zu\n", offsetof(pd_block_info, style));
    printf("pd_block_info.list %zu\n", offsetof(pd_block_info, list));
    printf("pd_block_info.break_kind %zu\n", offsetof(pd_block_info, break_kind));
    printf("pd_block_info.text_length %zu\n", offsetof(pd_block_info, text_length));
    printf("pd_block_info.revision %zu\n", offsetof(pd_block_info, revision));
    printf("pd_char_props %zu\n", sizeof(pd_char_props));
    printf("pd_char_props.mask %zu\n", offsetof(pd_char_props, mask));
    printf("pd_char_props.family %zu\n", offsetof(pd_char_props, family));
    printf("pd_char_props.size %zu\n", offsetof(pd_char_props, size));
    printf("pd_char_props.weight %zu\n", offsetof(pd_char_props, weight));
    printf("pd_char_props.italic %zu\n", offsetof(pd_char_props, italic));
    printf("pd_char_props.color %zu\n", offsetof(pd_char_props, color));
    printf("pd_char_props.background %zu\n", offsetof(pd_char_props, background));
    printf("pd_char_props.underline %zu\n", offsetof(pd_char_props, underline));
    printf("pd_char_props.strike %zu\n", offsetof(pd_char_props, strike));
    printf("pd_char_props.shift %zu\n", offsetof(pd_char_props, shift));
    printf("pd_char_props.letter_space %zu\n", offsetof(pd_char_props, letter_space));
    printf("pd_char_props.kerning %zu\n", offsetof(pd_char_props, kerning));
    printf("pd_char_props.lang %zu\n", offsetof(pd_char_props, lang));
    printf("pd_char_props.small_caps %zu\n", offsetof(pd_char_props, small_caps));
    printf("pd_char_props.link_target %zu\n", offsetof(pd_char_props, link_target));
    printf("pd_char_props.caps %zu\n", offsetof(pd_char_props, caps));
    printf("pd_char_props.hidden %zu\n", offsetof(pd_char_props, hidden));
    printf("pd_char_props.position %zu\n", offsetof(pd_char_props, position));
    printf("pd_char_props.revision %zu\n", offsetof(pd_char_props, revision));
    printf("pd_char_props.family_ea %zu\n", offsetof(pd_char_props, family_ea));
    printf("pd_char_props.family_cs %zu\n", offsetof(pd_char_props, family_cs));
    printf("pd_char_props.size_cs %zu\n", offsetof(pd_char_props, size_cs));
    printf("pd_char_props.weight_cs %zu\n", offsetof(pd_char_props, weight_cs));
    printf("pd_char_props.italic_cs %zu\n", offsetof(pd_char_props, italic_cs));
    printf("pd_revision %zu\n", sizeof(pd_revision));
    printf("pd_revision.kind %zu\n", offsetof(pd_revision, kind));
    printf("pd_revision.author %zu\n", offsetof(pd_revision, author));
    printf("pd_revision.date %zu\n", offsetof(pd_revision, date));
    printf("pd_comment %zu\n", sizeof(pd_comment));
    printf("pd_comment.author %zu\n", offsetof(pd_comment, author));
    printf("pd_comment.date %zu\n", offsetof(pd_comment, date));
    printf("pd_comment.text %zu\n", offsetof(pd_comment, text));
    printf("pd_comment.text_len %zu\n", offsetof(pd_comment, text_len));
    printf("pd_comment.parent %zu\n", offsetof(pd_comment, parent));
    printf("pd_comment.resolved %zu\n", offsetof(pd_comment, resolved));
    printf("pd_comment.range %zu\n", offsetof(pd_comment, range));
    printf("pd_para_props %zu\n", sizeof(pd_para_props));
    printf("pd_para_props.mask %zu\n", offsetof(pd_para_props, mask));
    printf("pd_para_props.align %zu\n", offsetof(pd_para_props, align));
    printf("pd_para_props.indent_left %zu\n", offsetof(pd_para_props, indent_left));
    printf("pd_para_props.indent_right %zu\n", offsetof(pd_para_props, indent_right));
    printf("pd_para_props.indent_first %zu\n", offsetof(pd_para_props, indent_first));
    printf("pd_para_props.space_before %zu\n", offsetof(pd_para_props, space_before));
    printf("pd_para_props.space_after %zu\n", offsetof(pd_para_props, space_after));
    printf("pd_para_props.line_spacing %zu\n", offsetof(pd_para_props, line_spacing));
    printf("pd_para_props.keep_with_next %zu\n", offsetof(pd_para_props, keep_with_next));
    printf("pd_para_props.keep_lines %zu\n", offsetof(pd_para_props, keep_lines));
    printf("pd_para_props.widows %zu\n", offsetof(pd_para_props, widows));
    printf("pd_para_props.orphans %zu\n", offsetof(pd_para_props, orphans));
    printf("pd_para_props.page_break_before %zu\n", offsetof(pd_para_props, page_break_before));
    printf("pd_para_props.hyphenate %zu\n", offsetof(pd_para_props, hyphenate));
    printf("pd_para_props.break_mode %zu\n", offsetof(pd_para_props, break_mode));
    printf("pd_para_props.next_style %zu\n", offsetof(pd_para_props, next_style));
    printf("pd_para_props.border_color %zu\n", offsetof(pd_para_props, border_color));
    printf("pd_para_props.border_width %zu\n", offsetof(pd_para_props, border_width));
    printf("pd_para_props.shading %zu\n", offsetof(pd_para_props, shading));
    printf("pd_para_props.direction %zu\n", offsetof(pd_para_props, direction));
    printf("pd_para_props.ntabs %zu\n", offsetof(pd_para_props, ntabs));
    printf("pd_para_props.tabs %zu\n", offsetof(pd_para_props, tabs));
    printf("pd_para_props.tab_interval %zu\n", offsetof(pd_para_props, tab_interval));
    printf("pd_para_props.contextual %zu\n", offsetof(pd_para_props, contextual));
    printf("pd_para_props.border_sides %zu\n", offsetof(pd_para_props, border_sides));
    printf("pd_para_props.border_space %zu\n", offsetof(pd_para_props, border_space));
    printf("pd_para_props.snap_grid %zu\n", offsetof(pd_para_props, snap_grid));
    printf("pd_tab_stop %zu\n", sizeof(pd_tab_stop));
    printf("pd_tab_stop.position %zu\n", offsetof(pd_tab_stop, position));
    printf("pd_tab_stop.align %zu\n", offsetof(pd_tab_stop, align));
    printf("pd_tab_stop.leader %zu\n", offsetof(pd_tab_stop, leader));
    printf("pd_list_level %zu\n", sizeof(pd_list_level));
    printf("pd_list_level.format %zu\n", offsetof(pd_list_level, format));
    printf("pd_list_level.start %zu\n", offsetof(pd_list_level, start));
    printf("pd_list_level.text %zu\n", offsetof(pd_list_level, text));
    printf("pd_list_level.indent %zu\n", offsetof(pd_list_level, indent));
    printf("pd_list_level.hanging %zu\n", offsetof(pd_list_level, hanging));
    printf("pd_list_level.restart_after %zu\n", offsetof(pd_list_level, restart_after));
    printf("pd_list_level.label_family %zu\n", offsetof(pd_list_level, label_family));
    printf("pd_list_level.label_size %zu\n", offsetof(pd_list_level, label_size));
    printf("pd_list_level.label_weight %zu\n", offsetof(pd_list_level, label_weight));
    printf("pd_list_level.label_italic %zu\n", offsetof(pd_list_level, label_italic));
    printf("pd_list_level.label_color %zu\n", offsetof(pd_list_level, label_color));
    printf("pd_run %zu\n", sizeof(pd_run));
    printf("pd_run.start %zu\n", offsetof(pd_run, start));
    printf("pd_run.end %zu\n", offsetof(pd_run, end));
    printf("pd_run.format %zu\n", offsetof(pd_run, format));
    printf("pd_inline %zu\n", sizeof(pd_inline));
    printf("pd_inline.kind %zu\n", offsetof(pd_inline, kind));
    printf("pd_inline.resource %zu\n", offsetof(pd_inline, resource));
    printf("pd_inline.width %zu\n", offsetof(pd_inline, width));
    printf("pd_inline.height %zu\n", offsetof(pd_inline, height));
    printf("pd_inline.depth %zu\n", offsetof(pd_inline, depth));
    printf("pd_inline.field %zu\n", offsetof(pd_inline, field));
    printf("pd_inline.target %zu\n", offsetof(pd_inline, target));
    printf("pd_inline.level %zu\n", offsetof(pd_inline, level));
    printf("pd_inline.name %zu\n", offsetof(pd_inline, name));
    printf("pd_inline.source %zu\n", offsetof(pd_inline, source));
    printf("pd_inline.source_len %zu\n", offsetof(pd_inline, source_len));
    printf("pd_inline.user %zu\n", offsetof(pd_inline, user));
    printf("pd_inline.title %zu\n", offsetof(pd_inline, title));
    printf("pd_inline.title_len %zu\n", offsetof(pd_inline, title_len));
    printf("pd_inline.alt %zu\n", offsetof(pd_inline, alt));
    printf("pd_inline.alt_len %zu\n", offsetof(pd_inline, alt_len));
    printf("pd_para_attrs %zu\n", sizeof(pd_para_attrs));
    printf("pd_para_attrs.quote_depth %zu\n", offsetof(pd_para_attrs, quote_depth));
    printf("pd_para_attrs.task %zu\n", offsetof(pd_para_attrs, task));
    printf("pd_para_attrs.loose %zu\n", offsetof(pd_para_attrs, loose));
    printf("pd_para_attrs.lang %zu\n", offsetof(pd_para_attrs, lang));
    printf("pd_para_attrs.cont %zu\n", offsetof(pd_para_attrs, cont));
    printf("pd_para_attrs.div_class %zu\n", offsetof(pd_para_attrs, div_class));
    printf("pd_font_info %zu\n", sizeof(pd_font_info));
    printf("pd_font_info.alt %zu\n", offsetof(pd_font_info, alt));
    printf("pd_font_info.generic %zu\n", offsetof(pd_font_info, generic));
    printf("pd_font_info.pitch %zu\n", offsetof(pd_font_info, pitch));
    printf("pd_font_info.panose %zu\n", offsetof(pd_font_info, panose));
    printf("pd_font_info.charset %zu\n", offsetof(pd_font_info, charset));
    printf("pd_float_props %zu\n", sizeof(pd_float_props));
    printf("pd_float_props.placement %zu\n", offsetof(pd_float_props, placement));
    printf("pd_float_props.wrap %zu\n", offsetof(pd_float_props, wrap));
    printf("pd_float_props.width %zu\n", offsetof(pd_float_props, width));
    printf("pd_float_props.width_fraction %zu\n", offsetof(pd_float_props, width_fraction));
    printf("pd_float_props.span_columns %zu\n", offsetof(pd_float_props, span_columns));
    printf("pd_float_props.gap %zu\n", offsetof(pd_float_props, gap));
    printf("pd_float_props.sequence %zu\n", offsetof(pd_float_props, sequence));
    printf("pd_float_props.offset_x %zu\n", offsetof(pd_float_props, offset_x));
    printf("pd_float_props.offset_y %zu\n", offsetof(pd_float_props, offset_y));
    printf("pd_float_props.offset_from %zu\n", offsetof(pd_float_props, offset_from));
    printf("pd_section_props %zu\n", sizeof(pd_section_props));
    printf("pd_section_props.page_width %zu\n", offsetof(pd_section_props, page_width));
    printf("pd_section_props.page_height %zu\n", offsetof(pd_section_props, page_height));
    printf("pd_section_props.margin_top %zu\n", offsetof(pd_section_props, margin_top));
    printf("pd_section_props.margin_bottom %zu\n", offsetof(pd_section_props, margin_bottom));
    printf("pd_section_props.margin_left %zu\n", offsetof(pd_section_props, margin_left));
    printf("pd_section_props.margin_right %zu\n", offsetof(pd_section_props, margin_right));
    printf("pd_section_props.header_distance %zu\n", offsetof(pd_section_props, header_distance));
    printf("pd_section_props.footer_distance %zu\n", offsetof(pd_section_props, footer_distance));
    printf("pd_section_props.columns %zu\n", offsetof(pd_section_props, columns));
    printf("pd_section_props.column_gap %zu\n", offsetof(pd_section_props, column_gap));
    printf("pd_section_props.first_page_number %zu\n", offsetof(pd_section_props, first_page_number));
    printf("pd_section_props.page_number_format %zu\n", offsetof(pd_section_props, page_number_format));
    printf("pd_section_props.title_page %zu\n", offsetof(pd_section_props, title_page));
    printf("pd_section_props.facing_pages %zu\n", offsetof(pd_section_props, facing_pages));
    printf("pd_section_props.header %zu\n", offsetof(pd_section_props, header));
    printf("pd_section_props.header_first %zu\n", offsetof(pd_section_props, header_first));
    printf("pd_section_props.header_even %zu\n", offsetof(pd_section_props, header_even));
    printf("pd_section_props.footer %zu\n", offsetof(pd_section_props, footer));
    printf("pd_section_props.footer_first %zu\n", offsetof(pd_section_props, footer_first));
    printf("pd_section_props.footer_even %zu\n", offsetof(pd_section_props, footer_even));
    printf("pd_section_props.continuous %zu\n", offsetof(pd_section_props, continuous));
    printf("pd_section_props.page_breaking %zu\n", offsetof(pd_section_props, page_breaking));
    printf("pd_section_props.footnote_skip %zu\n", offsetof(pd_section_props, footnote_skip));
    printf("pd_section_props.add_spacing %zu\n", offsetof(pd_section_props, add_spacing));
    printf("pd_section_props.line_numbers %zu\n", offsetof(pd_section_props, line_numbers));
    printf("pd_section_props.line_number_start %zu\n", offsetof(pd_section_props, line_number_start));
    printf("pd_section_props.line_number_distance %zu\n", offsetof(pd_section_props, line_number_distance));
    printf("pd_section_props.line_number_restart %zu\n", offsetof(pd_section_props, line_number_restart));
    printf("pd_section_props.mirror_margins %zu\n", offsetof(pd_section_props, mirror_margins));
    printf("pd_section_props.gutter %zu\n", offsetof(pd_section_props, gutter));
    printf("pd_section_props.page_valign %zu\n", offsetof(pd_section_props, page_valign));
    printf("pd_section_props.line_pitch %zu\n", offsetof(pd_section_props, line_pitch));
    printf("pd_table_props %zu\n", sizeof(pd_table_props));
    printf("pd_table_props.width %zu\n", offsetof(pd_table_props, width));
    printf("pd_table_props.align %zu\n", offsetof(pd_table_props, align));
    printf("pd_table_props.header_rows %zu\n", offsetof(pd_table_props, header_rows));
    printf("pd_table_props.cell_padding %zu\n", offsetof(pd_table_props, cell_padding));
    printf("pd_table_props.border %zu\n", offsetof(pd_table_props, border));
    printf("pd_table_props.border_color %zu\n", offsetof(pd_table_props, border_color));
    printf("pd_table_props.ncols %zu\n", offsetof(pd_table_props, ncols));
    printf("pd_table_props.col_width %zu\n", offsetof(pd_table_props, col_width));
    printf("pd_table_props.indent %zu\n", offsetof(pd_table_props, indent));
    printf("pd_table_props.width_pct %zu\n", offsetof(pd_table_props, width_pct));
    printf("pd_table_props.border_sides %zu\n", offsetof(pd_table_props, border_sides));
    printf("pd_table_props.cell_padding_v %zu\n", offsetof(pd_table_props, cell_padding_v));
    printf("pd_cell_props %zu\n", sizeof(pd_cell_props));
    printf("pd_cell_props.col_span %zu\n", offsetof(pd_cell_props, col_span));
    printf("pd_cell_props.valign %zu\n", offsetof(pd_cell_props, valign));
    printf("pd_cell_props.background %zu\n", offsetof(pd_cell_props, background));
    printf("pd_cell_props.merge_up %zu\n", offsetof(pd_cell_props, merge_up));
    printf("pd_cell_props.min_height %zu\n", offsetof(pd_cell_props, min_height));
    printf("pd_cell_props.border_set %zu\n", offsetof(pd_cell_props, border_set));
    printf("pd_cell_props.border_on %zu\n", offsetof(pd_cell_props, border_on));
    printf("pd_cell_props.border_width %zu\n", offsetof(pd_cell_props, border_width));
    printf("pd_cell_props.border_color %zu\n", offsetof(pd_cell_props, border_color));
    printf("pd_cell_props.edge_width %zu\n", offsetof(pd_cell_props, edge_width));
    printf("pd_change %zu\n", sizeof(pd_change));
    printf("pd_change.kind %zu\n", offsetof(pd_change, kind));
    printf("pd_change.block %zu\n", offsetof(pd_change, block));
    printf("pd_change.style %zu\n", offsetof(pd_change, style));
    printf("pd_change.revision %zu\n", offsetof(pd_change, revision));
    printf("pd_layout_info %zu\n", sizeof(pd_layout_info));
    printf("pd_layout_info.pages %zu\n", offsetof(pd_layout_info, pages));
    printf("pd_layout_info.paragraphs_broken %zu\n", offsetof(pd_layout_info, paragraphs_broken));
    printf("pd_layout_info.paragraphs_reused %zu\n", offsetof(pd_layout_info, paragraphs_reused));
    printf("pd_layout_info.float_pages %zu\n", offsetof(pd_layout_info, float_pages));
    printf("pd_layout_info.overfull %zu\n", offsetof(pd_layout_info, overfull));
    printf("pd_layout_info.variants %zu\n", offsetof(pd_layout_info, variants));
    printf("pd_page_info %zu\n", sizeof(pd_page_info));
    printf("pd_page_info.width %zu\n", offsetof(pd_page_info, width));
    printf("pd_page_info.height %zu\n", offsetof(pd_page_info, height));
    printf("pd_page_info.section %zu\n", offsetof(pd_page_info, section));
    printf("pd_page_info.number %zu\n", offsetof(pd_page_info, number));
    printf("pd_page_info.label %zu\n", offsetof(pd_page_info, label));
    printf("pd_page_info.float_page %zu\n", offsetof(pd_page_info, float_page));
    printf("pd_page_info.first %zu\n", offsetof(pd_page_info, first));
    printf("pd_page_info.last %zu\n", offsetof(pd_page_info, last));
    printf("pd_draw %zu\n", sizeof(pd_draw));
    printf("pd_draw.kind %zu\n", offsetof(pd_draw, kind));
    printf("pd_draw.x %zu\n", offsetof(pd_draw, x));
    printf("pd_draw.y %zu\n", offsetof(pd_draw, y));
    printf("pd_draw.w %zu\n", offsetof(pd_draw, w));
    printf("pd_draw.h %zu\n", offsetof(pd_draw, h));
    printf("pd_draw.glyph %zu\n", offsetof(pd_draw, glyph));
    printf("pd_draw.font %zu\n", offsetof(pd_draw, font));
    printf("pd_draw.size %zu\n", offsetof(pd_draw, size));
    printf("pd_draw.color %zu\n", offsetof(pd_draw, color));
    printf("pd_draw.resource %zu\n", offsetof(pd_draw, resource));
    printf("pd_draw.block %zu\n", offsetof(pd_draw, block));
    printf("pd_draw.offset %zu\n", offsetof(pd_draw, offset));
    printf("pd_draw.region %zu\n", offsetof(pd_draw, region));
    printf("pd_draw.text %zu\n", offsetof(pd_draw, text));
    printf("pd_draw.scale %zu\n", offsetof(pd_draw, scale));
    printf("pd_draw.points %zu\n", offsetof(pd_draw, points));
    printf("pd_draw.npoints %zu\n", offsetof(pd_draw, npoints));
    printf("pd_draw.path_flags %zu\n", offsetof(pd_draw, path_flags));
    printf("pd_draw.line_width %zu\n", offsetof(pd_draw, line_width));
    printf("pd_draw.fill %zu\n", offsetof(pd_draw, fill));
    printf("pd_draw.clip_x %zu\n", offsetof(pd_draw, clip_x));
    printf("pd_draw.clip_y %zu\n", offsetof(pd_draw, clip_y));
    printf("pd_draw.clip_w %zu\n", offsetof(pd_draw, clip_w));
    printf("pd_draw.clip_h %zu\n", offsetof(pd_draw, clip_h));
    printf("pd_draw.fill2 %zu\n", offsetof(pd_draw, fill2));
    printf("pd_draw.grad %zu\n", offsetof(pd_draw, grad));
    printf("pd_draw.grad_angle %zu\n", offsetof(pd_draw, grad_angle));
    printf("pd_draw.rotation %zu\n", offsetof(pd_draw, rotation));
    printf("pd_draw.flip %zu\n", offsetof(pd_draw, flip));
    printf("pd_draw.clip_points %zu\n", offsetof(pd_draw, clip_points));
    printf("pd_draw.clip_npoints %zu\n", offsetof(pd_draw, clip_npoints));
    printf("pd_markup_item %zu\n", sizeof(pd_markup_item));
    printf("pd_markup_item.kind %zu\n", offsetof(pd_markup_item, kind));
    printf("pd_markup_item.id %zu\n", offsetof(pd_markup_item, id));
    printf("pd_markup_item.range %zu\n", offsetof(pd_markup_item, range));
    printf("pd_markup_item.x %zu\n", offsetof(pd_markup_item, x));
    printf("pd_markup_item.y %zu\n", offsetof(pd_markup_item, y));
    printf("pd_markup_item.top %zu\n", offsetof(pd_markup_item, top));
    printf("pd_markup_item.bottom %zu\n", offsetof(pd_markup_item, bottom));
    printf("pd_markup_item.color %zu\n", offsetof(pd_markup_item, color));
    printf("pd_pdf_options %zu\n", sizeof(pd_pdf_options));
    printf("pd_pdf_options.compress %zu\n", offsetof(pd_pdf_options, compress));
    printf("pd_pdf_options.outlines %zu\n", offsetof(pd_pdf_options, outlines));
    printf("pd_pdf_options.title %zu\n", offsetof(pd_pdf_options, title));
    printf("pd_pdf_options.author %zu\n", offsetof(pd_pdf_options, author));
    return 0;
}
