/*
 * Parade Unicode properties (Unicode 15.1), tables in pd_unidata.c
 * generated by tools/gen_unidata.py
 */

#ifndef PD_UNIDATA_H
#define PD_UNIDATA_H

#include <stdint.h>

/* line break classes, LB1 resolution applied (AI SG XX -> AL, SA -> CM/AL, CJ -> NS) */
enum {
    LB_BK, LB_CR, LB_LF, LB_CM, LB_NL, LB_SG, LB_WJ, LB_ZW, LB_GL, LB_SP, LB_ZWJ, LB_B2, LB_BA, LB_BB, LB_HY, LB_CB,
    LB_CL, LB_CP, LB_EX, LB_IN, LB_NS, LB_OP, LB_QU, LB_IS, LB_NU, LB_PO, LB_PR, LB_SY, LB_AI, LB_AK, LB_AL, LB_AP,
    LB_AS, LB_CJ, LB_EB, LB_EM, LB_H2, LB_H3, LB_HL, LB_ID, LB_JL, LB_JV, LB_JT, LB_RI, LB_SA, LB_VF, LB_VI, LB_XX
};

enum {
    GCB_OTHER, GCB_CR, GCB_LF, GCB_CONTROL, GCB_EXTEND, GCB_ZWJ, GCB_RI, GCB_PREPEND, GCB_SPACINGMARK, GCB_L, GCB_V,
    GCB_T, GCB_LV, GCB_LVT
};

enum {
    INCB_NONE, INCB_LINKER, INCB_CONSONANT, INCB_EXTEND
};

enum {
    BC_L, BC_R, BC_AL, BC_EN, BC_ES, BC_ET, BC_AN, BC_CS, BC_NSM, BC_BN, BC_B, BC_S, BC_WS, BC_ON, BC_LRE, BC_LRO,
    BC_RLE, BC_RLO, BC_PDF, BC_LRI, BC_RLI, BC_FSI, BC_PDI
};

extern const uint16_t pd_uni_lb_1[], pd_uni_gcb_1[], pd_uni_bidi_1[];
extern const uint8_t pd_uni_lb_2[], pd_uni_gcb_2[], pd_uni_bidi_2[];
extern const uint32_t pd_uni_brackets[][3];
extern const int32_t pd_uni_nbrackets;
extern const uint32_t pd_uni_mirrors[][2];
extern const int32_t pd_uni_nmirrors;

#define PD_UNI_LOOKUP(t, cp) ((cp) < 0x110000 ? pd_uni_##t##_2[pd_uni_##t##_1[(cp) >> 8] * 256 + ((cp) & 0xFF)] : 0)

static inline int pd_uni_lb(uint32_t cp) {
    return cp < 0x110000 ? (PD_UNI_LOOKUP(lb, cp) & 0x3F) : LB_AL;
}

static inline int pd_uni_lb_eawide(uint32_t cp) {
    return (PD_UNI_LOOKUP(lb, cp) & 0x40) != 0;
}

static inline int pd_uni_gcb(uint32_t cp) {
    return PD_UNI_LOOKUP(gcb, cp) & 0x0F;
}

static inline int pd_uni_incb(uint32_t cp) {
    return (PD_UNI_LOOKUP(gcb, cp) >> 4) & 3;
}

static inline int pd_uni_pi(uint32_t cp) {
    return (PD_UNI_LOOKUP(gcb, cp) & 0x40) != 0;
}

static inline int pd_uni_pf(uint32_t cp) {
    return (PD_UNI_LOOKUP(gcb, cp) & 0x80) != 0;
}

static inline int pd_uni_bidi(uint32_t cp) {
    return PD_UNI_LOOKUP(bidi, cp) & 0x1F;
}

static inline int pd_uni_extpict(uint32_t cp) {
    return (PD_UNI_LOOKUP(bidi, cp) & 0x20) != 0;
}

static inline int pd_uni_unassigned(uint32_t cp) {
    return (PD_UNI_LOOKUP(bidi, cp) & 0x40) != 0;
}

/* the mirrored code point, or cp itself */
uint32_t pd_uni_mirror(uint32_t cp);
/* bracket pair: 1 opening, 2 closing, 0 none; *pair receives the other bracket */
int pd_uni_bracket(uint32_t cp, uint32_t* pair);

#endif /* PD_UNIDATA_H */
